# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: windows-latest

stages:
- stage: Build_Java
  displayName: Build Java
  jobs:
    - job: Build_Project
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: test
          
- stage: Powershell_Script
  displayName: Creating workItem
  jobs:
    - job: WorkItemCreation
      steps:
        - task: PowerShell@2
          inputs:
            targetType: filePath
            filePath: ./createBug.ps1
          condition: succeededOrFailed()
          env:
            workitemType: Bug
            Area: DevSecOps
            AssignedTo: Aquib
            Reason: testcasefailed
            tags: Automation
